stone:
  name: 'Configurations'
  display_name: 'tmod_conf'
  permission_name: ['role-access-settings', 'role-access-languages', 'role-access-templates']
  menu_type: ~
  menu_icon: 'fe fe-settings'
  enable: 1,
  publish: 'public'
